name: Terraform CI/CD
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"

jobs:
  terraform:
    runs-on: ubuntu-latest
 
    defaults:
      run:
        shell: bash
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
 
    - name: Terraform Init
      run: terraform init -backend-config="tfstate.config"
 
    - name: Terraform Validate
      run: terraform validate
 
    - name: Terraform Plan
      run: terraform plan -out=tfplan
 
    - name: Terraform Apply
      if: github.event_name == 'push'
      run: terraform apply -input=false tfplan
 
    - name: Terraform Destroy
      if: github.event_name == 'push'
      run: terraform destroy --auto-approve
