name: Terraform CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup_and_init_terraform:
    runs-on: ubuntu-latest
    steps:
      - &checkout_repo
        name: Checkout repository
        uses: actions/checkout@v2
      
      - &setup_terraform
        name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        run: terraform init -backend-config="tfstate.config"

  terraform_validate:
    runs-on: ubuntu-latest
    needs: setup_and_init_terraform
    steps:
      - *checkout_repo
      - *setup_terraform
      - name: Terraform Validate
        run: terraform validate

  terraform_plan:
    runs-on: ubuntu-latest
    needs: setup_and_init_terraform
    steps:
      - *checkout_repo
      - *setup_terraform
      - name: Terraform Plan
        run: terraform plan -out=tfplan

  terraform_apply:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: terraform_plan
    steps:
      - *checkout_repo
      - *setup_terraform
      - name: Terraform Apply
        run: terraform apply -input=false tfplan

  terraform_destroy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: terraform_apply
    steps:
      - *checkout_repo
      - *setup_terraform
      - name: Terraform Destroy
        run: terraform destroy --auto-approve
