name: Terraform CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Manual trigger
    inputs:
      command:
        description: 'Apply infrastructure'
        required: true
        default: 'apply'  # Default to apply

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend-config="tfstate.config"

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      if: github.event_name == 'workflow_dispatch'
      run: terraform plan -out=tfplan

    - name: Confirm Apply
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.command == 'apply'
      run: |
        echo "Do you want to apply the changes?(yes|no)"
        read -r answer
        if [ "$answer" != "yes" ]; then
          echo "Apply canceled."
          exit 1
        fi

    - name: Terraform Apply
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.command == 'apply'
      run: terraform apply -input=false tfplan

    - name: Confirm Destroy
      run: |
        echo "Do you want to destroy the resources?"
        read -r answer
        if [ "$answer" != "yes" ]; then
          echo "Destroy canceled."
          exit 1
        fi

    - name: Terraform Destroy
      run: terraform destroy --auto-approve
