name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init -backend-config="tfstate.config"
      - name: Validate Terraform
        working-directory: ./terraform
        run: terraform validate

  plan:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init -backend-config="tfstate.config"
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan
      - name: Save Plan
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: terraform/tfplan

  apply:
    runs-on: ubuntu-latest
    needs: plan
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init -backend-config="tfstate.config"
      - name: Download Plan
        uses: actions/download-artifact@v2
        with:
          name: tfplan
          path: terraform/
      - name: Apply Terraform
        working-directory: ./terraform
        run: terraform apply -input=false tfplan

  destroy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init -backend-config="tfstate.config"
      - name: Destroy Infrastructure
        working-directory: ./terraform
        run: terraform destroy --auto-approve
